#!/usr/bin/env zsh

if [[ $EUID -ne 0 ]] && [[ -n "$TERMINATOR_UUID" ]]; then
    #(printf "Hostname:\t$(hostname -s )\n" && sw_vers) | lolcat

    #COWS=(/usr/share/cowsay/cows/*.cow)
    #RAND_COW=$(($RANDOM % $(ls /usr/local/share/cows/*.cow | wc -l)))
    #RAND_COW=$(($RANDOM % $(find /usr/share/cowsay/cows/ -name "*.cow" | wc -l)))
    
    #neofetch && fortune | cowsay -f ${COWS[$RAND_COW]} | lolcat && echo
    #neofetch --ascii_distro macos && fortune | cowsay -f ${COWS[$RAND_COW]} | lolcat && echo
    #neofetch --ascii_distro macos && fortune | lolcat && echo
    fastfetch -l macos --logo-type auto; echo
    #fastfetch --logo-type auto; echo
    fortune | lolcat && echo
    
    #neofetch --ascii_distro Ubuntu-Budgie --color_blocks off
fi
