#!/usr/bin/env bash

if [[ $EUID -ne 0 ]] && [[ -n "$TERMINATOR_UUID" ]]; then
    #(printf "Hostname:\t$(hostname -s )\n" && sw_vers) | lolcat
    
    #COWS=(/usr/share/cows/*.cow)
    #RAND_COW=$(($RANDOM % $(ls /usr/local/share/cows/*.cow | wc -l)))
    #RAND_COW=$(($RANDOM % $(find /usr/share/cows/ -name "*.cow" | wc -l)))
    #neofetch --ascii_distro BlackArch #&& fortune | cowsay -f ${COWS[$RAND_COW]} | lolcat && echo
    fastfetch -l arch --logo-type auto --logo-color-1 red --logo-color-2 red --color red
    
fi
